menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/ahmclishihao
    csdn: http://blog.csdn.net/ahmclishihao
    about: /about/
# Rss: /atom.xml

favicon: /favicon.ico
logo: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
